#!/usr/bin/perl
use strict;
use warnings;

print <<EOF
<?xml version='1.0' encoding='UTF-8'?>
<!DOCTYPE html
  PUBLIC '-//W3C//DTD XHTML 1.0 Strict//EN' 'http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd'>
<html xmlns='http://www.w3.org/1999/xhtml' lang='en' xml:lang='en'>
<head>
<base href='http://jw209508.hopto.org/fortexle/'/>
<title>ForTeXle, i.e. LaTeX tricks</title>
<link rel='stylesheet' href='index.css' type='text/css'/>
</head>
<body>
EOF
;

for my $filename (@ARGV)
{
  print "<div>\n";
  $filename =~ s/[.]tex$//;
  open IN, '<', "$filename.tex" or die $filename;

  my $target = undef;
  my %buckets;
  while (<IN>)
  {
    if (m{^% <([a-z]+)>$})
    {
      $target = $1;
      $buckets{$target} = '';
      next;
    }
    if (m{^% </[a-z]+>$})
    {
      $target = undef;
    }
    next unless defined $target;
    $buckets{$target} .= $_;
  }

  close IN;

  foreach (keys %buckets)
  {
    $buckets{$_} =~ s/^\s+//;
    $buckets{$_} =~ s/\s+$//;
  }

  if (defined $buckets{'requisites'})
  {
    $_ = $buckets{'requisites'};
    s/&/&amp;/g; s/</&lt;/g; s/>/&gt;/g;
    print "<div>\n<h1>Requisites</h1>\n<pre>\n$_\n</pre>\n</div>\n";
  }

  if (defined $buckets{'trunk'})
  {
    $_ = $buckets{'trunk'};
    s/&/&amp;/g; s/</&lt;/g; s/>/&gt;/g;
    print "<div>\n<h1>Solution</h1>\n<pre>\n$_\n</pre>\n</div>\n";
  }

  if (defined $buckets{'example'})
  {
    $_ = $buckets{'example'};
    s/&/&amp;/g; s/</&lt;/g; s/>/&gt;/g;
    print "<div>\n<h1>Example of use</h1>\n<pre>\n$_\n</pre>\n</div>\n";
  }

  my $fileinfo = `/usr/bin/file "$filename.png"`;
  $fileinfo =~ m{ ([0-9]+) x ([0-9]+),};
  my ($width, $height) = ($1, $2);

  print "<div class='result'>\n<h1>Result</h1>\n<img src='$filename.png' width='$width' height='$height' alt=' '/>\n</div>\n";

  print "</div>"
}

print <<EOF
</body>
</html>
EOF
;

# vim:ts=2 sw=2 et
